
steps:
  - name: Update Composer
    command: '/usr/local/bin/composer self-update
  - name: Get proper drush version
    command: 'composer global require drush/drush:dev-master ; cd /usr/local/bin ; mv drush drush7 ; ln -s $HOME/.composer/vendor/bin/drush drush'
  - name: Install drush-master for d8
    command: 'composer global require drush/drush:8.* ; cd /usr/local/bin ; mv drush drush7 ; ln -s $HOME/.composer/vendor/bin/drush drush'
  - name: Run the profile script
    command: './$SRC_DIR/.probo-profile-build.sh'
  - name: Run install
    command: "drush -y site-install --root=/var/www/html social --db-url='mysqli://root:root@db:3306/social'"
  - name: Set file directory permissions
    command: 'chown -R www-data:www-data /var/www/html/sites/default/files'
  - name: Rebuild caches
    command: 'drush cr'
  - name: Run behat tests
    command: 'cd /var/www/html/profiles/social/tests ; composer install ; ./bin/behat --profile probo'
