<?php

use Drupal\Core\Entity\EntityInterface;

/**
 * Implements hook_entity_presave().
 * @param \Drupal\Core\Entity\EntityInterface $entity
 */
function social_pathauto_entity_presave(EntityInterface $entity) {
  $content_type = \Drupal::entityQuery('node')->condition('type', 'page')->execute();
  $nodes = \Drupal::service('entity.manager')
    ->getStorage('node')
    ->loadMultiple($content_type);

  if($entity->getEntityType() === 'node') {
    $nodes->path['pathauto'] = TRUE;
  }
}

///**
// * Implements hook_preprocess().
// */
//function social_pathauto_preprocess(&$variables, $hook) {
//  $query_node_types = \Drupal::entityQuery('node')
//    ->condition('type', 'page')
//    ->execute();
//  $nodes = \Drupal::service('entity.manager')
//    ->getStorage('node')
//    ->loadMultiple($query_node_types);
//
//  dpm($nodes);
//}